# Generated by Django 3.1.4 on 2022-06-01 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=100)),
                ('owner_mobile', models.BigIntegerField()),
                ('model_name', models.CharField(max_length=20)),
                ('condition', models.CharField(choices=[('Poor', 'pur'), ('Fair', 'fer'), ('Good', 'gud'), ('Excellent', 'exl')], max_length=100)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='blog/')),
                ('price', models.IntegerField()),
                ('year', models.DateField()),
                ('make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.company')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobile', models.BigIntegerField()),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='sales.listing')),
            ],
        ),
    ]
