# Generated by Django 3.1.4 on 2022-06-01 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SellCarListing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=100)),
                ('owner_mobile', models.BigIntegerField()),
                ('make', models.CharField(max_length=50)),
                ('model_name', models.CharField(max_length=20)),
                ('condition', models.CharField(choices=[('Poor', 'pur'), ('Fair', 'fer'), ('Good', 'gud'), ('Excellent', 'exl')], max_length=90)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='blog/')),
                ('price', models.IntegerField()),
                ('year', models.DateField()),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CarSaleRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobile', models.BigIntegerField()),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.sellcarlisting')),
            ],
        ),
    ]
