# Generated by Django 3.1.4 on 2022-06-02 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CarCompany',
        ),
        migrations.RemoveField(
            model_name='sellcarlisting',
            name='slug',
        ),
        migrations.AddField(
            model_name='sellcarlisting',
            name='sold',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sellcarlisting',
            name='condition',
            field=models.CharField(choices=[('Poor', 'poor'), ('Fair', 'fair'), ('Good', 'good'), ('Excellent', 'excellent')], max_length=90),
        ),
    ]
